### ISSUE TITLE
Battery and F4 clash

### ISSUE THREAD

**Issue by simonclark63** [ThomasDavid0/Placebo_F3A#2]
Hi Tom,
I am probably being a bit dense here but on the fuselage GA, it looks like the battery location shown has it clashing with F4. Does the battery actually sit above F4 or does F4 need to be cut down, or am I missing something?
Thanks
Simon

**Comment by ThomasDavid0** [comment]
Hi Simon,
I decided to raise the battery a bit late in the design process to remove a bit of yaw - roll coupling I saw in my old plane. If anything it could go a bit higher as there is still a very slight mix required, but its easy enough to raise the battery further by adding some padding underneath it and more difficult to lower it. I don't think any of the parametric links actually depend on the battery in the fusion model, its just there for reference, mainly because the fuselage is very narrow and I wanted to be sure you could get it in. 
cheers,
Tom

**Comment by simonclark63** [comment]
Hi Tom,
That all makes perfect sense. Thanks for the speedy reply.
Cheers
Simon
